spring.application.name=booking-com

# db

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/spring-things-again?createDatabaseIfNotExist=true
spring.datasource.username=robert
spring.datasource.password=hue
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# jpa/hib

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB53Dialect
spring.batch.jdbc.initialize-schema=always